#!/usr/bin/env bash

		#Apache2 installation 
		echo “installing Apache2”
		apt-get update
		apt-get install -y apache2
		if ! [ -L /var/www ]; then
		  rm -rf /var/www
		  ln -fs /vagrant /var/www
		fi

		#Git installation
		echo “installing Git”
		apt-get install git -y > /dev/null

		#MySQL installation
		echo “installing MySQL”
		apt-get install debconf-utils -y > /dev/null
		#MySQL installation requires setting up password. To automate this, I used the following two lines of code.
		debconf-set-selections <<< "mysql-server mysql-server/root_password password Pass12"
		debconf-set-selections <<< "mysql-server mysql-server/root_password_again password Pass12"
		
		apt-get update
		apt-get -y install mysql-server > /dev/null

		#Installation of the required software is done! 		

		#The following three if statements are used to test wether git, MySQL, and Apache has been installed.
		#It first check the status of a package, if the status contained “ok installed” returns 1, otherwise returns 0.
		#For git, since the example shows that it should be installed, we check if the returned value is 1, then print 
		#a custom message.
		if [ $(dpkg-query -W -f='${Status}' git 2>/dev/null | grep -c "ok installed") -eq 1 ];
		then 
			echo “git… Installed”
		fi
		
		#Here we check wether MySQL has been installed. The custom message is also created. 
		if [ $(dpkg-query -W -f='${Status}' mysql 2>/dev/null | grep -c "ok installed") -eq 0 ];
		then 
			echo “mysql… Not Installed!”
		fi

		#Here we check wether Apache has been installed. The custom message is also created. 
		if [ $(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed") -eq 1 ];
		then 
			echo “apache… Installed”
		fi
		
		#The following line of code is to automatically add the use “pythian” to the system
		#Creating a new user is an interactive process, which has to be handled.
		sudo adduser pythian --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password

		

		#Making the required directory and clone a git repository in that directory
		mkdir -p opt/code
		git clone https://github.com/pythian/DevOps_Cloud_Automation_Engineer_Project.git opt/code

		#The ownership and permission is change for the code directory and all of the files within that
		#to “drwxr-x--- 3 pythian pythian 4096 Aug 10 15:30 code” (This is the output that I got during the testing procedure).
		chmod 750 -R opt/code
		sudo chown -R pythian:pythian opt/code


